version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: django-backend
    volumes:
      - static_volume:/app/dist/static  # 挂载静态文件
    expose:
      - 8000

  nginx:
    build:
      context: ./nginx
    container_name: nginx-proxy
    ports:
      - 8080:80
    depends_on:
      - backend
    volumes:
      - static_volume:/app/dist/static  # 挂载静态文件

volumes:
  static_volume:
