# Generated by Django 5.1.3 on 2024-12-11 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                ("ID_number", models.CharField(max_length=20)),
                ("Contact", models.CharField(max_length=255)),
                ("Creation_date", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                ("position_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("responsibilities", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                ("education_id", models.AutoField(primary_key=True, serialize=False)),
                ("institution", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=100)),
                ("major", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="hr_system.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("experience_id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience",
                        to="hr_system.employee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hr_system.position",
            ),
        ),
    ]
