# Generated by Django 5.1.3 on 2024-12-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="ID_number",
            field=models.CharField(max_length=18),
        ),
        migrations.RemoveField(
            model_name="employee",
            name="position",
        ),
        migrations.AlterField(
            model_name="position",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="position",
            name="responsibilities",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ManyToManyField(to="hr_system.position"),
        ),
    ]
