# Generated by Django 5.1.3 on 2024-12-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hr_system",
            "0002_alter_employee_id_number_remove_employee_position_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="Creation_date",
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
