# Generated by Django 5.1.3 on 2024-12-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_system", "0003_alter_employee_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="Creation_date",
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
