# Generated by Django 5.1.3 on 2024-12-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_system", "0004_alter_employee_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.ManyToManyField(blank=True, to="hr_system.position"),
        ),
    ]
