# Generated by Django 5.1.3 on 2024-12-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_system", "0005_alter_employee_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="Contact",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="ID_number",
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
